import type { Project } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
    const placeholder = PlaceHolderImages.find(p => p.id === id);
    return {
        url: placeholder?.imageUrl || `https://picsum.photos/seed/${id}/400/200`,
        hint: placeholder?.imageHint || 'abstract',
    };
};

export const projects: Project[] = [
  {
    id: 'inv-1',
    name: 'نظارة طبية ذكية',
    inventor: 'دانه الشمراني',
    description: 'نظارة طبية ذكية للكشف المبكر عن مؤشرات الأمراض الوراثية عبر تحليل البكتيريا في الفم باستخدام مستشعرات دقيقة متصلة بتطبيق.',
    cost: 20000,
    amountRaised: 15000,
    investors: 12,
    expectedProfit: 20,
    duration: 'سنة',
    category: 'تقنية طبية',
    image: getImage('inventor-1').url,
    imageHint: getImage('inventor-1').hint,
    publishDate: '2024-07-15',
  },
  {
    id: 'inv-2',
    name: 'سوار صحي ذكي',
    inventor: 'أمينة الحربي',
    description: 'سوار صحي ذكي لمرضى السكري يقيس التغيرات الجلدية الدقيقة المرتبطة بمستوى السكر دون وخز، ويرتبط بتطبيق تنبيهات فورية.',
    cost: 30000,
    amountRaised: 10000,
    investors: 8,
    expectedProfit: 25,
    duration: 'سنة ونصف',
    category: 'تقنية طبية',
    image: getImage('inventor-2').url,
    imageHint: getImage('inventor-2').hint,
    publishDate: '2024-07-10',
  },
  {
    id: 'inv-3',
    name: 'جهاز زراعي صغير',
    inventor: 'أرام العتيبي',
    description: 'جهاز زراعي صغير يعمل بالطاقة الشمسية لقياس رطوبة التربة وتحديد الري المثالي تلقائيًا للمزارع الصغيرة.',
    cost: 25000,
    amountRaised: 22000,
    investors: 20,
    expectedProfit: 22,
    duration: 'سنة',
    category: 'تقنية زراعية',
    image: getImage('inventor-3').url,
    imageHint: getImage('inventor-3').hint,
    publishDate: '2024-06-28',
  },
  {
    id: 'inv-4',
    name: 'تطبيق طبي بالذكاء الاصطناعي',
    inventor: 'لمار المطيري',
    description: 'تطبيق طبي يعتمد على الذكاء الاصطناعي لتحليل أعراض النساء المبكرة وربطها بأقرب تخصص طبي مناسب.',
    cost: 40000,
    amountRaised: 5000,
    investors: 3,
    expectedProfit: 30,
    duration: 'سنتان',
    category: 'صحة رقمية',
    image: getImage('inventor-4').url,
    imageHint: getImage('inventor-4').hint,
    publishDate: '2024-06-20',
  },
  {
    id: 'inv-5',
    name: 'كبسولات عضوية للتربة',
    inventor: 'جنان آل قشاد',
    description: 'كبسولات عضوية لتحسين خصوبة التربة تعتمد على بكتيريا نافعة محلية، تقلل استخدام الأسمدة الكيميائية بنسبة 40%.',
    cost: 18000,
    amountRaised: 18000,
    investors: 35,
    expectedProfit: 28,
    duration: 'سنة',
    category: 'الزراعة المستدامة',
    image: getImage('inventor-5').url,
    imageHint: getImage('inventor-5').hint,
    publishDate: '2024-05-30',
  },
  {
    id: 'inv-6',
    name: 'جهاز تعقيم منزلي ذكي',
    inventor: 'ريتاج الميبر',
    description: 'جهاز منزلي ذكي لتعقيم الخضار والفواكه بالأوزون الطبيعي دون مواد كيميائية، مخصص للعائلات.',
    cost: 22000,
    amountRaised: 12000,
    investors: 15,
    expectedProfit: 24,
    duration: 'سنة',
    category: 'أجهزة منزلية',
    image: getImage('inventor-6').url,
    imageHint: getImage('inventor-6').hint,
    publishDate: '2024-05-15',
  },
  {
    id: 'inv-7',
    name: 'منصة تسويق زراعي',
    inventor: 'لتين الشمراني',
    description: 'منصة إلكترونية لتسويق المنتجات الزراعية المحلية مباشرة من المزارع إلى المستهلك مع نظام تتبع جودة.',
    cost: 35000,
    amountRaised: 30000,
    investors: 28,
    expectedProfit: 27,
    duration: 'سنة ونصف',
    category: 'تجارة إلكترونية',
    image: getImage('inventor-7').url,
    imageHint: getImage('inventor-7').hint,
    publishDate: '2024-05-01',
  },
];
